export const projects = [
  {
    title: 'Resume',
    description: "My Resume created with nothing but HTML and a bit of in line CSS. ",
      image: '/images/htmlround.png',
      tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/HTML-Resume',
    visit: 'https://hidden-brook-04981.herokuapp.com/',
    id: 0,
  },
  { 
    title: 'CSS',
    description:"A contact form created with HTML and CSS.",
    image: '/images/cssround.png',
    tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/CSS-Site',
    visit: 'https://still-cliffs-93056.herokuapp.com/?',
    id: 1,
  },
  {
    title: 'Fibonacci Generator',
    description: "A small app I made from scratch to better understand JavaScript.",
      image: '/images/javascriptsquare.png',
      tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/Fibonacci-Generator',
    visit: 'https://lit-retreat-52204.herokuapp.com/',
    id: 2,
  },
  {
    title: 'To Do List',
    description: "Created with Express JavaScript and uses and Mongoose backend to store.",
    image: '/images/mongoose-square.jpg',
    tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/To-Do-List',
    visit: 'https://polar-beach-66346.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Newsletter Signup Form',
    description: "Created with EJS and Mailchimp API to handle the HTTPS requests. I created the logo myself using Canva.",
    image: '/images/mailchimp.jpg',
    tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/Newsletter-Signup',
    visit: 'https://calm-plateau-03960.herokuapp.com/',
    id: 4,
  },
  {
    title: 'App Brewery Tin Dog',
    description: "A recreation of Tin Dog to practice BootStrap. Practiced using Cards, Carosels, Headers, Footers.",
    image: '/images/bootstrap.jpeg',
    tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://google.com',
    visit: 'https://ancient-mesa-81490.herokuapp.com/',
    id: 5,
  },
  {
    title: 'Weather App API',
    description: "Created with Javascript and uses Open Weather Map API. Renders the results as an HTTP form. Also renders a failure page if false city entered.",
    image: '/images/sun.png',
    tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/Weather-App',
    visit: 'https://obscure-hamlet-00075.herokuapp.com/',
    id: 6,
  },
  {
    title: 'Authentication App',
    description: "An App that practices Google Single Sign On. Once your logged in you can access any secret that you post. Also uses a Mongoose backend database.",
    image: '/images/oauth.png',
    tags: ['Please note the App takes 5 seconds to load'],
    source: 'https://github.com/KBCodes2021/Secret-App',
    visit: 'https://whispering-earth-86781.herokuapp.com/?',
    id: 7,
  },
  {
    title: 'Media Converter',
    description: "",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'React Clock',
    description: "Use States to maintain constant ticking of time.",
    image: '/images/react.png',
    tags: ['Please note the App takes 30 seconds to load'],
    source: 'https://github.com/KBCodes2021/React-Clock',
    visit: 'https://sheltered-temple-41914.herokuapp.com/',
    id: 9,
  },
  {
    title: 'React To Do List',
    description: "List created with React, focused on using Components and Params.",
    image: '/images/react.png',
    tags: ['Please note the App takes 30 seconds to load'],
    source: 'https://github.com/KBCodes2021/React-to-do-list',
    visit: 'https://serene-shore-98722.herokuapp.com/?',
    id: 10,
  },
  {
    title: 'User Submit Form',
    description: "A 3 Input Cell Form with Submit Button created in React.",
    image: '/images/react.png',
    tags: ['Please note the App takes 30 seconds to load'],
    source: 'https://github.com/KBCodes2021/React-signup-form',
    visit: 'https://quiet-shore-03523.herokuapp.com/',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started my journey', },
  { year: 2021, text: 'Completed Boot Camp', },
  { year: 2022, text: 'Started focusing on MERN Development', },
  { year: 2022, text: 'Started looking for Freelance Projects', },
  { year: 2022, text: 'Started looking for an Intership or Junior Developer roles', },
];